import type { Metadata } from "next";
import { Nunito, Inter } from "next/font/google";
import "./../globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";
import Footer from "@/components/Footer";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CepuIn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      lang="en"
      className={`${nunito.variable} ${inter.variable} h-full antialiased`}
    >
      <div className="min-h-full flex flex-col">
        <NavbarWrapper />
        {children}
        <Footer />
      </div>
    </div>
  );
}
