export const laporanData = [
  {
    id: "cmnbxyj9e0008j3maa6ih0obv",
    judul: "Lampu jalan mati",
    deskripsi: "Lampu jalan di depan gang 3 sudah mati 2 hari",
    kategori: "Listrik",
    fotoBefore: "https://res.cloudinary.com/demo/image/upload/sample.jpg",
    fotoAfter: null,
    status: "Selesai",
    kredibel: true,
    createdAt: "2026-03-29T15:56:10.371Z",
    updatedAt: "2026-03-29T15:56:10.371Z",
    userId: "cmnbxyix90002j3ma360kuvyf",
    user: {
      nama: "Budi Santoso",
      username: "budi",
    },
  },
  {
    id: "cmnbxyj9f0009j3map0mx5kii",
    judul: "Ubin trotoar lepas",
    deskripsi: "Ubin trotoar depan pos ronda sudah lepas dan berbahaya",
    kategori: "Bangunan",
    fotoBefore: "https://res.cloudinary.com/demo/image/upload/sample.jpg",
    fotoAfter: null,
    status: "Proses",
    kredibel: true,
    createdAt: "2026-03-29T15:56:10.371Z",
    updatedAt: "2026-03-29T15:56:10.371Z",
    userId: "cmnbxyix90002j3ma360kuvyf",
    user: {
      nama: "Budi Santoso",
      username: "budi",
    },
  },
  {
    id: "cmnbxyj9f000aj3masmlhz790",
    judul: "Sampah menumpuk",
    deskripsi: "Sampah di TPS depan balai RT sudah menumpuk sejak seminggu",
    kategori: "Kebersihan",
    fotoBefore: "https://res.cloudinary.com/demo/image/upload/sample.jpg",
    fotoAfter: null,
    status: "Baru",
    kredibel: false,
    createdAt: "2026-03-29T15:56:10.371Z",
    updatedAt: "2026-03-29T15:56:10.371Z",
    userId: "cmnbxyj1j0004j3ma1uxshpoh",
    user: {
      nama: "Siti Rahayu",
      username: "siti",
    },
  },
  {
    id: "cmnbxyj9f000bj3mabpsliqc7",
    judul: "Keran air bocor",
    deskripsi: "Keran air di mushola bocor dan menggenangi lantai",
    kategori: "Bangunan",
    fotoBefore: "https://res.cloudinary.com/demo/image/upload/sample.jpg",
    fotoAfter: null,
    status: "Selesai",
    kredibel: true,
    createdAt: "2026-03-29T15:56:10.371Z",
    updatedAt: "2026-03-29T15:56:10.371Z",
    userId: "cmnbxyj1j0004j3ma1uxshpoh",
    user: {
      nama: "Siti Rahayu",
      username: "siti",
    },
  },
  {
    id: "cmnbxyj9f000cj3ma1sjxahp5",
    judul: "CCTV mati",
    deskripsi: "CCTV di pintu masuk perumahan tidak menyala",
    kategori: "Keamanan",
    fotoBefore: "https://res.cloudinary.com/demo/image/upload/sample.jpg",
    fotoAfter: null,
    status: "Ditolak",
    kredibel: false,
    createdAt: "2026-03-29T15:56:10.371Z",
    updatedAt: "2026-03-29T15:56:10.371Z",
    userId: "cmnbxyj1j0004j3ma1uxshpoh",
    user: {
      nama: "Siti Rahayu",
      username: "siti",
    },
  },
  {
    id: "cmnbxyj9f000dj3maqdficgz3",
    judul: "Got mampet",
    deskripsi: "Saluran air di RT mampet dan menyebabkan banjir kecil",
    kategori: "Kebersihan",
    fotoBefore: "https://res.cloudinary.com/demo/image/upload/sample.jpg",
    fotoAfter: null,
    status: "Baru",
    kredibel: false,
    createdAt: "2026-03-29T15:56:10.371Z",
    updatedAt: "2026-03-29T15:56:10.371Z",
    userId: "cmnbxyj5u0006j3mabd2rvn5e",
    user: {
      nama: "Eko Prasetyo",
      username: "eko",
    },
  },
  {
    id: "cmnbxyj9f000ej3maylh7lmdr",
    judul: "Tiang listrik miring",
    deskripsi:
      "Tiang listrik di ujung jalan kelihatan miring setelah hujan deras",
    kategori: "Listrik",
    fotoBefore: "https://res.cloudinary.com/demo/image/upload/sample.jpg",
    fotoAfter: null,
    status: "Proses",
    kredibel: true,
    createdAt: "2026-03-29T15:56:10.371Z",
    updatedAt: "2026-03-29T15:56:10.371Z",
    userId: "cmnbxyj5u0006j3mabd2rvn5e",
    user: {
      nama: "Eko Prasetyo",
      username: "eko",
    },
  },
];